<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>gudusoft.gsqlparser.demos.removevars</RootNamespace>
    <AssemblyName>removevars</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="gudusoft.gsqlparser" Version="$(GspVersion)" />
  </ItemGroup>
</Project>
